//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mix
    {
        public int mid { get; set; }
        public string mname { get; set; }
        public int pid { get; set; }
        public int uid { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
